name: Deploy Local Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Rsync to local folder
        run: |
          rsync -av ./ /var/www/html
